---
# task file to install macports using pkgutil

- name: darwin | macosx | check if package installer file exists
  stat:
    path="/tmp/{{ macports_installer[ major_version ][ 'name' ] }}"
  register: f

- name: darwin | macosx | download macports package installer
  get_url:
    url="https://distfiles.macports.org/MacPorts/{{ macports_installer[ major_version ][ 'name' ] }}"
    dest=/tmp
    sha256sum={{ macports_installer[ major_version ][ 'sha256' ] }}
    owner=root
    group=wheel
    mode=0644
  sudo: yes
  when: not f.stat.exists

- name: darwin | macosx | install macports
  command: "installer -verbose -pkg {{ macports_installer[ major_version ][ 'name' ] }} -target /"
  args:
    chdir: /tmp/
  sudo: yes

- name: darwin | macosx | update ports tree and rebuild installation if needed
  command: port -v selfupdate
  sudo: yes

- name: darwin | macosx | remove macports package installer
  file:
    path="/tmp/{{ macports_installer[ major_version ][ 'name' ] }}"
    state=absent
  sudo: yes

- name: darwin | macosx | upgrade outdated ports
  command: port -v upgrade outdated
  sudo: yes
  when: macports_upgrade_outdated
