---
# task file to install macports using pkgutil

- name: darwin | macosx | check if package installer file exists
  stat:
    path="/tmp/{{ ansiblebit_macports_installer[ major_version ][ 'name' ] }}"
  register: f

- name: darwin | macosx | download macports package installer
  get_url:
    url="https://distfiles.macports.org/MacPorts/{{ ansiblebit_macports_installer[ major_version ][ 'name' ] }}"
    dest=/tmp
    sha256sum={{ ansiblebit_macports_installer[ major_version ][ 'sha256' ] }}
    owner=root
    group=wheel
    mode=0644
  sudo: yes
  when: not f.stat.exists

- name: darwin | macosx | install macports
  shell: "installer -verbose -pkg /tmp/{{ ansiblebit_macports_installer[ major_version ][ 'name' ] }} -target /"
  sudo: yes

- name: darwin | macosx | update ports tree and rebuild installation if needed
  shell: port -v selfupdate
  sudo: yes

- name: darwin | macosx | remove macports package installer
  file:
    path="/tmp/{{ ansiblebit_macports_installer[ major_version ][ 'name' ] }}"
    state=absent
  sudo: yes
